name: UI tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # 3.14 лучше не использовать в CI
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          playwright install --with-deps

      - name: Run tests
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  publish-report:
    if: always()
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # Подтягиваем историю (для трендов)
      - name: Load history
        run: |
          if [ -d gh-pages/history ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi

      # Генерация отчёта
      - name: Generate Allure report
        uses: andgineer/allure-report@v3
        with:
          allure-results: allure-results
          allure-report: allure-report
          allure-history: history

      - name: Debug report
        run: |
          echo "=== ALLURE REPORT ==="
          ls -R allure-report || echo "NO REPORT"

      # Деплой (ВАЖНО: именно allure-report)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          force_orphan: true